#!/usr/bin/env node
// Build frontend/app/water.js (WATER_POLYGONS) — the second land-avoidance layer.
// `natural=coastline` stops at a river's tidal limit; the upper Fraser, harbour
// basins, etc. are OSM water polygons absent from coastline.js, so vessels there
// read as on-land. This layer is subtracted at runtime: pointOnLand = inLand && !inWater.
//
// Water exists ONLY to re-open narrow navigable features the coarse coastline closed,
// so it is always surveyed at the FINEST resolution (≈25 m). Per the resolution policy
// (worker/CLAUDE.md): simplify tol ≤ ⅓ of the narrowest channel to keep open. Do NOT
// coarsen this layer.
//
// Prerequisite — fetch OSM water for a FINE zone (Overpass bbox = south,west,north,east).
// Fetch PER fine-zone (a global/combined query truncates):
//   curl -sS -H "User-Agent: vessel-tracker/1.0" "https://overpass-api.de/api/interpreter" \
//     --data-urlencode 'data=[out:json][timeout:180];(
//       way["natural"="water"](49.00,-123.30,49.40,-122.70);
//       relation["natural"="water"](49.00,-123.30,49.40,-122.70);
//       way["waterway"="riverbank"](49.00,-123.30,49.40,-122.70);
//       relation["waterway"="riverbank"](49.00,-123.30,49.40,-122.70);
//     );out body geom;' -o /tmp/osm_water_fraser.json
//
// Usage:  node scripts/build-water.mjs /tmp/osm_water_fraser.json [more_dumps...]
// Multiple dumps (one per fine zone) are merged. Run from worker/.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { assembleWater } from './lib-osm-water.mjs';

// Resolution: fine only (see policy). Drop ponds smaller than a vessel cares about.
const SIMPLIFY_KM = 0.025;     // ≈25 m
const DROP_SPAN_KM = 0.10;     // skip water bodies whose outer ring spans < 100 m
const HOLE_DROP_SPAN_KM = 0.05;

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(SCRIPT_DIR, '../../frontend/app/water.js');
const INPUTS = process.argv.slice(2);
if (INPUTS.length === 0) { console.error('usage: build-water.mjs <dump.json> [more...]'); process.exit(1); }

const R_KM = 6371.0;
function haversineKm(la1, lo1, la2, lo2) {
  const r = Math.PI / 180, dLat = (la2 - la1) * r, dLon = (lo2 - lo1) * r;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(la1 * r) * Math.cos(la2 * r) * Math.sin(dLon / 2) ** 2;
  return 2 * R_KM * Math.asin(Math.sqrt(a));
}
// Perp distance (km) of point p from segment a→b ([lon,lat]), equirectangular-local.
function perpKm(p, a, b) {
  const lat0 = ((a[1] + b[1]) / 2) * Math.PI / 180, kx = 111.32 * Math.cos(lat0), ky = 111.32;
  const ax = a[0] * kx, ay = a[1] * ky, bx = b[0] * kx, by = b[1] * ky, px = p[0] * kx, py = p[1] * ky;
  const dx = bx - ax, dy = by - ay, L2 = dx * dx + dy * dy;
  let t = L2 > 0 ? ((px - ax) * dx + (py - ay) * dy) / L2 : 0;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}
// Iterative Douglas-Peucker at a fixed tolerance (km), preserving ring closure.
function simplifyRing(pts, tolKm) {
  if (pts.length <= 4) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = 1; keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [lo, hi] = stack.pop();
    if (hi - lo < 2) continue;
    let maxD = 0, maxI = -1;
    for (let i = lo + 1; i < hi; i++) { const d = perpKm(pts[i], pts[lo], pts[hi]); if (d > maxD) { maxD = d; maxI = i; } }
    if (maxI !== -1 && maxD > tolKm) { keep[maxI] = 1; stack.push([lo, maxI], [maxI, hi]); }
  }
  const out = [];
  for (let i = 0; i < pts.length; i++) if (keep[i]) out.push(pts[i]);
  return out;
}
function spanKm(ring) {
  let mnx = 999, mxx = -999, mny = 999, mxy = -999;
  for (const [lo, la] of ring) { if (lo < mnx) mnx = lo; if (lo > mxx) mxx = lo; if (la < mny) mny = la; if (la > mxy) mxy = la; }
  return haversineKm(mny, mnx, mxy, mxx);
}

// ── Build ─────────────────────────────────────────────────────────────────────
let raw = [];
for (const f of INPUTS) raw = raw.concat(assembleWater(JSON.parse(fs.readFileSync(f, 'utf8')).elements));

const round = n => Math.round(n * 1e5) / 1e5;
let droppedSmall = 0, holesKept = 0;
const polys = [];
for (const { outer, holes } of raw) {
  if (spanKm(outer) < DROP_SPAN_KM) { droppedSmall++; continue; }
  const o = simplifyRing(outer, SIMPLIFY_KM).map(([lo, la]) => [round(la), round(lo)]);
  if (o.length < 4) continue;
  const h = holes
    .filter(hr => spanKm(hr) >= HOLE_DROP_SPAN_KM)
    .map(hr => simplifyRing(hr, SIMPLIFY_KM).map(([lo, la]) => [round(la), round(lo)]))
    .filter(hr => hr.length >= 4);
  holesKept += h.length;
  polys.push(h.length ? { o, h } : { o });
}
polys.sort((a, b) => b.o.length - a.o.length);

const totalVerts = polys.reduce((s, p) => s + p.o.length + (p.h ?? []).reduce((t, hr) => t + hr.length, 0), 0);
const body = `// Auto-generated by build-water.mjs — do not edit manually.
// Source: OpenStreetMap natural=water / waterway=riverbank (via Overpass), per fine
// zone. The SECOND land-avoidance layer: subtracted at runtime so navigable rivers /
// harbour basins the coastline layer closed read as water (pointOnLand = inLand &&
// !inWater). Each entry: { o: outer ring [[lat,lon],…], h?: hole rings (mid-water
// islands → land) }. Simplified at ≈${SIMPLIFY_KM * 1000} m (fine only — see resolution policy).
// ${polys.length} polygons, ${totalVerts} vertices, ${holesKept} holes.

export const WATER_POLYGONS = ${JSON.stringify(polys)};
`;
fs.writeFileSync(OUT, body);
const kb = (Buffer.byteLength(body) / 1024).toFixed(0);
console.log(`water polygons: ${raw.length} -> ${polys.length} kept (${droppedSmall} tiny dropped), ${holesKept} holes`);
console.log(`vertices: ${totalVerts}`);
console.log(`wrote ${OUT}  (${kb} KB)`);
