name = "vessel-tracker-api"
main = "src/index.ts"
compatibility_date = "2026-02-15"
workers_dev = true
minify = true

[vars]
ALLOWED_ORIGIN = "*"

[triggers]
crons = ["* * * * *", "*/5 * * * *", "0 * * * *"]

[[d1_databases]]
binding = "VESSELS_DB"
database_name = "vessel-tracker"
database_id = "1fc3b1b8-b293-49fd-951e-5765f184e44b"
